spring:
  application:
    name: server

server:
  port: 8089

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    register-with-eureka: false
    #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8089/eureka